INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Andronic','Larisa','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Arîcu','Aculina','conferențiar cercetător','doctor habilitat în științe chimice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Balan','Ion','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Begu','Adam','profesor universitar','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bejan','Iurie','conferențiar universitar','doctor în geografie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Boian','Ilie','conferențiar universitar','doctor în ştiinţe agricole',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bouroș','Pavlina','conferențiar cercetător','doctor în științe chimice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bucațel','Vasile','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bujoreanu','Nicolae','conferențiar cercetător','doctor habilitat în științe agricole',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bulat','Dumitru','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bulhac','Ion','conferențiar cercetător','doctor habilitat în științe chimice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bulimaga','Constantin','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bulimestru','Ion','conferențiar universitar','doctor în chimie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Burțeva','Svetlana','profesor cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cepoi','Liliana','conferențiar cercetător','doctor în biologie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cheaplyga','Andrei','','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Chiriac','Tatiana','conferențiar cercetător','doctor în biologie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ciochina','Nina','conferențiar cercetător','doctor în biologie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ciochină','Valentina','conferențiar cercetător','doctor în biologie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ciocîrlan','Alexandru','conferențiar cercetător','doctor în științe chimice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Codreanu','Igor','conferențiar cercetător','doctor în geografie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Comanici','Ion','profesor universitar','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Derjanschi','Valeriu','profesor cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dragancea','Diana','conferențiar cercetător','doctor în științe chimice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Drugociu','Gheorghe','profesor universitar','doctor în științe medicale',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Duca','Gheorghe','profesor universitar','doctor habilitat în chimie',1,'academician');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dumbrava','Vlada-Tatiana','','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Furdui','Teodor','doctor habilitat în științe biologice','academician',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ghendov','Veaceslav','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Gonța','Maria','profesor universitar','doctor habilitat în chimie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Gulea','Aurelian','profesor universitar','doctor habilitat în chimie',1,'academician');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Jigău','Gheorghe','conferențiar universitar','doctor în biologie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Leorda','Ana','conferențiar cercetător','doctor în biologie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Lupașcu','Galina','profesor universitar','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Macaev','Fliur','profesor universitar','doctor habilitat în științe chimice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Mereuță','Ion','profesor universitar','doctor habilitat în științe medicale',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Munteanu','Andrei','profesor universitar','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Munteanu-Molotievskiy','Natalia','','doctor în biologie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Nastas','Tudor','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Nistreanu','Victoria','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Povar','Igor','conferențiar cercetător','doctor habilitat în științe chimice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Puțuntică','Anatolie','conferențiar universitar','doctor în geografie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Roșca','Ion','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Rudic','Valeriu','profesor universitar','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sacară','Victoria','conferențiar universitar','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șeptițchi','Vladimir','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sîrbu','Tamara','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Strutinschi','Tudor','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șuleșco','Tatiana','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Tumanova','Lidia','conferențiar cercetător','doctor în chimie',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ungureanu','Laurenția','conferențiar cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Voloşciuc','Leonid','profesor cercetător','doctor habilitat în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Vrabie','Valeria','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Zamorzaeva-Orleanscaia','Irina','conferențiar cercetător','doctor în științe biologice',1);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Zubcov','Elena','profesor cercetător','doctor habilitat în științe biologic',1);
----------------------------------science_school_id
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Achimova','Elena','conferențiar cercetător','doctor habilitat în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Aruşanov','Ernest','profesor universitar','doctor habilitat în științe fizico-matematice',2,'academician');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bragaru','Tudor','profesor universitar','doctor în economie',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Căpățână','Gheorghe','profesor universitar','doctor în tehnică',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Paladi','Florentin','profesor universitar','doctor habilitat în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cojocaru','Svetlana','conferențiar cercetător','doctor habilitat în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Colibaba','Gleb','','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Culiuc','Leonid','profesor universitar','doctor habilitat în științe fizico-matematice',2,'academician');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Enachi','Nicolae','profesor universitar','doctor habilitat în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Mihailescu','Ion','profesor universitar','doctor(România)',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Hâncu','Boris','conferențiar universitar','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Kravțov','Victor','conferențiar cercetător','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Baca','Svetlana','conferențiar cercetător','doctor în științe chimice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Macovei','Mihai','conferențiar cercetător','doctor habilitat în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Moscalenco','Sveatoslav','profesor universitar','doctor habilitat în științe fizico-matematice',2,'academician');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Petic','Mircea','conferențiar cercetător','doctor în informatică',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Potlog','Tamara','conferențiar universitar','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Prepeliță','Aurelia','conferențiar universitar','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Şcerbacov','Victor','conferențiar cercetător','doctor habilitat în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Sidorenko','Anatolie','profesor universitar','doctor habilitat în științe fizico-matematice',2,'academician');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șikimaka','Olga','conferențiar cercetător','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sîrbu','Parascovia','conferențiar universitar','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Tighineanu','Ion','profesor universitar','doctor habilitat în științe fizico-matematice',2,'academician');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Vatavu','Sergiu','conferențiar cercetător','doctor în științe fizico-matematice',2);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Rusu','Marin','conferențiar cercetător','doctor în științe fizico-matematic',2);
---------------------------------------
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Andreeva','Tatiana','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bajura','Tudor','profesor cercetător','doctor habilitat în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bulat','Veronica','conferențiar universitar','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Buzdugan','Adriana','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Caprian','Iulia','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Castraveț','Lucia','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cazacu','Vitalie','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cociug','Victoria','conferențiar universitar','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cojocaru','Maria','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Colesnicova','Tatiana','conferențiar cercetător','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Crotenco','Iurie','profesor universitar','doctor habilitat în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Doga-Mîrzac','Mariana','conferențiar cercetător','doctor habilitat în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dolghi','Cristina','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dragomir','Lilia','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ganea','Victoria','profesor universitar','doctor habilitat în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Gîrlea','Mihai','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Golovataia','Liudmila','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Hamuraru','Maria','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Iordachi','Victoria','conferențiar cercetător','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Lușmanschi','Galina','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Mihaila','Svetlana','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Mulic','Andrei','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Onofrei','Alexandru','profesor universitar','doctor habilitat în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Perciun','Rodica','conferențiar cercetător','doctor habilitat în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Popa','Andrei','profesor universitar','doctor habilitat în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Postică','Maia','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șargu','Lilia','conferențiar universitar','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Savelieva','Galina','conferențiar cercetător','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Gagauz','Olga','conferențiar cercetător','doctor habilitat în sociologie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Şavga','Larisa','profesor universitar','doctor habilitat în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ștefaniuc','Olga','conferențiar universitar','doctor în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Stratan','Alexandru','profesor universitar','doctor habilitat în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Tcaci','Carolina','conferențiar universitar','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Timuș','Angela','conferențiar cercetător','doctor în științe economice',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ulian','Galina','profesor universitar','doctor habilitat în economie',3);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Prisăcaru','Veronica','conferențiar universitar','doctor în științe economic',3);
-----------------------------------
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Arhiliuc','Victoria','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Arseni','Alexandru','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Băieșu','Aurel','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Băieșu','Sergiu','profesor universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Balan','Oleg','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Barbăneagră','Alexei','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Belei','Elena','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Botnaru','Stela','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Brînză','Sergiu','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cârnaț','Teodor','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cebotari','Valentina','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Chiroșca','Dorian','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Chirtoacă','Leonid','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cimil','Dorin','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ciobanu','Rodica','conferențiar universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Coban','Igor','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cojocaru','Violeta','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Costache','Gheorghe','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cusnir','Valeriu','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cuznețov','Alexandru','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dolea','Igor','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dorul','Olga','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Eșanu','Adriana','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Gîrla','Lilia','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Grama','Mariana','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Gribincea','Lilia','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Grosu','Vladimir','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id,academician) VALUES ('Guceac','Ion','profesor universitar','doctor habilitat în drept',4,'acad.');
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Maimescu','Sava','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Manea','Vladislav','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Mihalache','Iurie','conferențiar universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Moraru','Victor','profesor universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Negru','Andrei','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Osoianu','Tudor','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Stebelkov','Vladimir','doctor în științe tehnice','FederațiaRusă',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Pantea','Oleg','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Pasat','Aurel','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Plotnic','Olesea','conferențiar universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Romandaș','Nicolae','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Rusu','Vitalie','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sadovei','Nicolae','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sârcu','Diana','conferențiar universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Slusarenco','Svetlana','conferențiar universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Smochină','Andrei','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Spînu','(Dumneanu)','conf. univ.','dr. în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Stati','Vitalie','profesor universitar','doctor în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ulianovschi','Xenofon','profesor universitar','doctor habilitat în drept',4);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Vizdoagă','Tatiana','conferențiar universitar','doctor în drep',4);
----------------------
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Anțibor','Ludmila','conferențiar universitar','doctor habilitat în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Beniuc','Valentin','conferențiar universitar','doctor habilitat în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bîrnaz','Nina','conferențiar universitar','doctor în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bodrug-Lungu','Valentina','profesor universitar','doctor habilitat în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bolea','Zinaida','conferențiar universitar','doctor în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cebotari','Svetlana','conferențiar universitar','doctor habilitat în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cheianu-Andrei','Diana','conferențiar universitar','doctor în sociologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cojocaru','Natalia','conferențiar universitar','doctor în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cornea','Sergiu','conferențiar universitar','doctor habilitat în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cuciureanu','Gheorghe','conferențiar cercetător','doctor habilitat în economie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dandara','Otilia','profesor universitar','doctor habilitat în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Darii','Ludmila','conferențiar universitar','doctor în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dulschi','Ion','conferențiar universitar','doctor în istorie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dulschi','Silvia','conferențiar universitar','doctor în istorie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ejova','Cristina','conferențiar universitar','doctor în politologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Goraș-Postică','Viorica','profesor universitar','doctor habilitat în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Guțu','Vladimir','profesor universitar','doctor habilitat în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Guțu','Zoia','conferențiar universitar','doctor în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Hîrbu','(Bencheci)','conferențiar universitar','doctor în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Isac','Oxana','conferențiar universitar','doctor în sociologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Malcoci','Ludmila','profesor cercetător','doctor habilitat în sociologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Milicenco','Stela','conferențiar universitar','doctor în sociologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Moraru','Victor','profesor universitar','doctor habilitat în politologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Oceretnîi','Anastasia','conferențiar universitar','doctor în sociologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Paladi','Oxana','conferențiar universitar','doctor în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Platon','Carolina','profesor universitar','doctor habilitat în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Popovici','Angela','conferențiar universitar','doctor în istorie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Potâng','Angela','conferențiar universitar','doctor în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Racu','Aurelia','profesor universitar','doctor habilitat în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Racu','Jana','profesor universitar','doctor habilitat în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Repida','Tatiana','conferențiar universitar','doctor în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Romandaș','Nicolae','profesor universitar','doctor în drept',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Roșca','Liudmila','conferențiar universitar','doctor habilitat în filosofie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Roșcovan','Mihail','conferențiar universitar','doctor în științe economice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Saca','Victor','profesor universitar','doctor habilitat în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sakovich','Vasil','profesor universitar','doctor habilitat în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șaptefrați','Tatiana','conferențiar universitar','doctor în biologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Şevciuc','Maia','profesor universitar','doctor în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sîmboteanu','Aurel','conferențiar universitar','doctor în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șoitu','Laurențiu','profesor universitar','doctor în pedagogie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Solomon','Constantin','profesor universitar','doctor habilitat în politologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Spătaru','Tatiana','conferențiar universitar','doctor habilitat în sociologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Sprîncean','Serghei','conferențiar universitar','doctor habilitat în politologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Stepanov','Georgeta','profesor universitar','doctor habilitat în științe ale comunicării',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Tarnovschi','Ana','conferențiar universitar','doctor în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Teosa','Valentina','profesor universitar','doctor habilitat în științe politice',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Tofan','Tatiana','conferențiar universitar','doctor în economie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Tolstaia','Svetlana','conferențiar universitar','doctor în psihologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Țurcan','Nelly','profesor universitar','doctor habilitat în sociologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Turco','Tatiana','conferențiar universitar','doctor în politologie',5);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Vasilescu','Grigore','profesor universitar','doctor habilitat în filosofi',5);
----------------------
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Anițoi','Galina','conferențiar cercetător','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bîrlădeanu','Virgiliu','conferențiar universitar','doctor în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bobînă','Gheorghe','profesor universitar','doctor habilitat în filosofie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Bogatu','Eugenia','conferențiar universitar','doctor în filosofie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cazacu-Țigaie','Adriana','conferențiar universitar','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cimpoi','Mihai','profesor universitar','doctor habilitat în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cincilei','Cornelia','conferențiar universitar','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Coandă','Svetlana','conferențiar universitar','doctor hab. în filosofie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Cojocaru','Gheorghe','conferențiar universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Condraticova','Liliana','conferențiar cercetător','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Condrea','Iraida','profesor universitar','doctor habilitat în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Constantinov','Valentin','conferențiar cercetător','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Corcinschi','Nina','conferențiar cercetător','doctor habilitat în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dănilă','Aurelian','profesor universitar','doctor habilitat în studiul artelor',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dragnev','Demir','profesor universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Dragnev','Emil','conferențiar universitar','doctor în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Druţă','Inga','conferențiar cercetător','doctor habilitat în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Enciu','Nicolae','profesor universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Eremia','Ion','profesor universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Eșanu','Andrei','profesor cercetător','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Fonari','Victoria','conferențiar universitar','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Ghilaș','Victor','conferențiar cercetător','doctor habilitat în studiul artelor',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Grădinaru','Angela','conferențiar universitar','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Grati','Aliona','profesor universitar','doctor habilitat în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Gumenâi','Ion','conferențiar universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Guțu','Ana','profesor universitar','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Hanganu','Aurelia','conferențiar universitar','doctor habilitat în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Lifari','Viorica','conferențiar universitar','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Manolache','Constantin','conferențiar universitar','doctor habilitat în științe politice',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Mincu','Eugenia','profesor universitar','doctor habilitat în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Molea','Viorica','conferențiar universitar','doctor habilitat în filol',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Nicoglo','Diana','conferențiar cercetător','doctor în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Pascaru','Ana','conferențiar cercetător','doctor habilitat în filosofie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Petrenco','Anatol','profesor universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Poștarenco','Dinu','conferențiar cercetător','doctor în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Rotaru','Liliana','conferențiar universitar','doctor în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Saharneanu','Eudochia','profesor universitar','doctor habilitat în filosofie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șarov','Igor','conferențiar universitar','doctor în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șimanschi','Ludmila','conferențiar cercetător','doctor în filologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șișcanu','Ion','profesor universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Șlapac','Mariana','conferențiar universitar','doctor habilitat în studiul artelor',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Solomon','Constantin','profesor universitar','doctor habilitat în politologie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Tomuleț','Valentin','profesor universitar','doctor habilitat în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Zanoci','Aurel','conferențiar universitar','doctor în istorie',6);
INSERT INTO supervisor(first_name, last_name, post,speciality, science_school_id) VALUES ('Zbanț','Ludmila','profesor universitar','doctor habilitat în filologi',6);