INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Marina', 'Slavinskaia', '', 1961, '', 'F', 6, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'CONTRACT', 212, 511.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Cristina', 'Nichita', '', 1992, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2021-11-01', 'LOW_FREQUENCY', 'BUDGET', 260, 621.04, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Ala', 'David', '', 1980, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'II', '2021-11-01', '2024-11-01', 'LOW_FREQUENCY', 'BUDGET', 260, 621.06, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Victor', 'Dulgher', '', 1994, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2021-11-01', 'LOW_FREQUENCY', 'BUDGET', 259, 613.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Sergiu', 'Serbinov', '', 1996, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'III', '2020-11-01', '2024-11-01', 'FREQUENCY', 'BUDGET', 259, 613.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Vladimir', 'Chitic', '', 1996, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'III', '2020-11-01', '2024-11-01', 'FREQUENCY', 'BUDGET', 259, 613.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Petru', 'Ciorba', '', 1992, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2019-11-01', '2021-11-01', 'LOW_FREQUENCY', 'BUDGET', 55, 166.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Victoria', 'Bogdan', '', 1982, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_I', '2017-11-01', '2021-10-31', 'FREQUENCY', 'BUDGET', 53, 165.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Andrei', 'Lungu', '', 1993, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'II', '2021-11-01', '2025-11-01', 'FREQUENCY', 'BUDGET', 52, 167.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Valeriu', 'Bodean', '', 1978, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2017-11-01', '2021-11-01', 'FREQUENCY', 'CONTRACT', 164, 554.03, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Aureliu', 'Postică', '', 1977, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2017-11-01', '2021-11-01', 'FREQUENCY', 'CONTRACT', 164, 554.03, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Aighiuni', 'Bahșiev', '', 1993, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-10-31', 'FREQUENCY', 'BUDGET', 54, 162.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Inna', 'Șargu-Rusu', '', 1987, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'IV', '2016-11-01', '2020-11-01', 'FREQUENCY', 'BUDGET', 11, 522.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Elena', 'Rusu', '', 1992, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2016-11-01', '2021-11-01', 'FREQUENCY', 'BUDGET', 89, 522.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Adela', 'Morcov', '', 1996, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'II', '2021-11-01', '2024-11-01', 'LOW_FREQUENCY', 'BUDGET', 164, 554.03, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Igor', 'Narolschi', '', 1969, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'IV', '2019-11-01', '2023-11-01', 'FREQUENCY', 'BUDGET', 79, 562.03, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Lilia', 'Lupașco', '', 1975, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'CONTRACT', 164, 561.01, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Iuliana', 'Stratan', '', 1981, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'BUDGET', 215, 572.02, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Gheorghe', 'Moșneaga', '', 1992, '', 'M', 1, '', 0, '', '', 'ACTIVE', null, 'IV', '2019-11-01', '2023-11-01', 'FREQUENCY', 'BUDGET', 214, 572.02, '', '');
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (nextval('student_sequence'), '', 'Viorica', 'Lupu', '', 1976, '', 'F', 1, '', 0, '', '', 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'BUDGET', 213, 572.02, '', '');

