INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (1, null, 'Marina', 'Slavinskaia', null, 1961, null, 'F', 6, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'CONTRACT', 212, 511.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (2, null, 'Cristina', 'Nichita', null, 1992, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2021-11-01', 'LOW_FREQUENCY', 'BUDGET', 260, 621.04, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (3, null, 'Ala', 'David', null, 1980, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'II', '2021-11-01', '2024-11-01', 'LOW_FREQUENCY', 'BUDGET', null, 621.06, 260, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (4, null, 'Victor', 'Dulgher', null, 1994, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2021-11-01', 'LOW_FREQUENCY', 'BUDGET', 259, 613.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (5, null, 'Sergiu', 'Serbinov', null, 1996, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'III', '2020-11-01', '2024-11-01', 'FREQUENCY', 'BUDGET', 259, 613.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (6, null, 'Vladimir', 'Chitic', null, 1996, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'III', '2020-11-01', '2024-11-01', 'FREQUENCY', 'BUDGET', 259, 613.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (7, null, 'Petru', 'Ciorba', null, 1992, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2019-11-01', '2021-11-01', 'LOW_FREQUENCY', 'BUDGET', 55, 166.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (8, null, 'Victoria', 'Bogdan', null, 1982, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_I', '2017-11-01', '2021-10-31', 'FREQUENCY', 'BUDGET', 53, 165.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (9, null, 'Andrei', 'Lungu', null, 1993, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'II', '2021-11-01', '2025-11-01', 'FREQUENCY', 'BUDGET', 52, 167.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (10, null, 'Valeriu', 'Bodean', null, 1978, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2017-11-01', '2021-11-01', 'FREQUENCY', 'CONTRACT', 164, 554.03, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (11, null, 'Aureliu', 'Postică', null, 1977, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2017-11-01', '2021-11-01', 'FREQUENCY', 'CONTRACT', 164, 554.03, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (12, null, 'Aighiuni', 'Bahșiev', null, 1993, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-10-31', 'FREQUENCY', 'BUDGET', 54, 162.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (13, null, 'Inna', 'Șargu-Rusu', null, 1987, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'IV', '2016-11-01', '2020-11-01', 'FREQUENCY', 'BUDGET', 11, 522.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (14, null, 'Elena', 'Rusu', null, 1992, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2016-11-01', '2021-11-01', 'FREQUENCY', 'BUDGET', 89, 522.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (15, null, 'Adela', 'Morcov', null, 1996, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'II', '2021-11-01', '2024-11-01', 'LOW_FREQUENCY', 'BUDGET', 164, 554.03, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (16, null, 'Igor', 'Narolschi', null, 1969, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'IV', '2019-11-01', '2023-11-01', 'FREQUENCY', 'BUDGET', 79, 562.03, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (17, null, 'Lilia', 'Lupașco', null, 1975, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'CONTRACT', 164, 561.01, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (18, null, 'Iuliana', 'Stratan', null, 1981, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'BUDGET', 215, 572.02, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (19, null, 'Gheorghe', 'Moșneaga', null, 1992, null, 'M', 1, null, 0, null, null, 'ACTIVE', null, 'IV', '2019-11-01', '2023-11-01', 'FREQUENCY', 'BUDGET', 214, 572.02, null, null);
INSERT INTO public.student (id, corporate_email, first_name, last_name, patronymic_name, year_birth, ident_number, gender, citizenship_id, diploma_series, diploma_number, personal_email, phone_number, status, registration_type, year_study, begin_studies, end_studies, study, financing, supervisor_id, speciality, science_topic, remark)
VALUES (20, null, 'Viorica', 'Lupu', null, 1976, null, 'F', 1, null, 0, null, null, 'ACTIVE', null, 'EXTRA_II', '2018-11-01', '2022-11-01', 'FREQUENCY', 'BUDGET', 213, 572.02, null, null);

