# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Set up PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install postgresql
        # Запуск службы PostgreSQL
        sudo service postgresql start
        # Создание пользователя суперпользователя
        sudo -u postgres psql -c "CREATE USER super_user WITH PASSWORD 'super_user'"
        # Создание базы данных и назначение пользователя суперпользователем базы данных
        sudo -u postgres createdb doctoral_registration
        sudo -u postgres psql -c "ALTER DATABASE doctoral_registration OWNER TO super_user"
        # Другие команды для настройки вашей базы данных, если это необходимо

    - name: Apply database migrations
      run: |
        mvn -B flyway:migrate --file pom.xml
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

