name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master", "develop", "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
          # Запуск службы PostgreSQL
          sudo service postgresql start
          # Создание пользователя суперпользователя
          sudo -u postgres psql -c "CREATE USER super_user WITH PASSWORD 'super_user'"
          # Создание базы данных и назначение пользователя суперпользователем базы данных
          sudo -u postgres createdb doctoral_registration
          sudo -u postgres psql -c "ALTER DATABASE doctoral_registration OWNER TO super_user"
          # Другие команды для настройки вашей базы данных, если это необходимо

      - name: Apply database migrations
        run: |
          mvn -B flyway:migrate --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: JaCoCo Test Coverage
        run: mvn jacoco:report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco/index.html

      - name: Check Test Coverage
        run: |
          # Здесь вы можете указать минимальный процент покрытия, который должен быть достигнут
          MIN_COVERAGE_PERCENT=80

          # Получите отчет о покрытии JaCoCo и извлеките процент покрытия
          COVERAGE_PERCENT=$(mvn jacoco:report -q -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn | grep -A 2 "Overall coverage" | tail -n 1 | awk '{print $3}' | tr -d '%')

          # Проверьте, достигнуто ли покрытие более или равно минимальному порогу
          if (( $COVERAGE_PERCENT < $MIN_COVERAGE_PERCENT )); then
            echo "Test coverage ($COVERAGE_PERCENT%) is below the minimum required coverage ($MIN_COVERAGE_PERCENT%). Commit aborted."
            exit 1
          fi


